@startwbs 主菜を作る
title 
主菜を作るwbs

endtitle
* ピーマンの肉詰めを作る
**[#SkyBlue] 下準備
***[#Yellow] ピーマンを洗う
***[#Yellow] ピーマンを縦に半分に切り種を取り除く
***[#Yellow] 玉ねぎをみじん切りにする
***[#Yellow] ボウルに挽肉、玉ねぎ、パン粉、牛乳、塩、胡椒、醤油を加える
***[#Yellow] よく混ぜて肉だねを作る
***[#Yellow] ピーマンに肉だねを詰める
**[#SkyBlue] 調理
***[#Yellow] 熱したフライパンに油を敷く
***[#Yellow] 肉だねを下にしてピーマンをフライパンに並べる
***[#Yellow] 焼き色がついたら、ひっくり返して蒸し焼きにする
**[#SkyBlue] 仕上げ
***[#Yellow] 焼きあがったピーマンの肉詰めをさらに盛り付ける

@endwbs
