@startwbs スープを作る
title
スープを作るwbs

endtitle
* 卵とわかめの中華スープを作る
**[#SkyBlue] 下準備
***[#Yellow] ねぎをみじん切りにする
***[#Yellow] 乾燥わかめを水で戻す
***[#Yellow] 卵を溶く
**[#SkyBlue] 調理
***[#Yellow] 鍋に水を入れて沸かす
***[#Yellow] 鍋に鶏がらスープの素、醤油、塩を入れて混ぜる
***[#Yellow] スープが沸騰したら、わかめを加える
***[#Yellow] 溶いた卵を流し入れ、卵が固まるまで軽く混ぜる
***[#Yellow] ねぎと卵を加えて混ぜる
**[#SkyBlue] 仕上げ
***[#Yellow] スープを盛り付ける 


@endwbs
