@startwbs 材料を買う
title
材料購入wbs

endtitle
* 材料を買う
**[#SkyBlue] 3人でお金を出しあう
***[#Yellow] スーパーでピーマンを買う
***[#Yellow] スーパーで挽肉を買う
***[#Yellow] スーパーで玉ねぎを買う
***[#Yellow] スーパーで牛乳を買う
***[#Yellow] スーパーでパン粉を買う
***[#Yellow] スーパーでほうれん草を買う
***[#Yellow] スーパーでかつお節を買う
***[#Yellow] スーパーで乾燥わかめを買う
***[#Yellow] スーパーでねぎを買う

@endwbs
