@startuml スープを作る
|ユーザー|
:卵とわかめの中華スープを作る;
start


:ねぎをみじん切りにする;
:乾燥わかめを水で戻す;
:卵を溶く;

fork
  :鍋に水を入れて沸かす;
  :鍋に鶏がらスープの素、醤油、塩を入れて混ぜる;
fork again
  :ボウルに乾燥わかめを戻す;
end fork

:スープが沸騰したら、わかめを加える;
:溶いた卵を流し入れ、卵が固まるまで軽く混ぜる;
:ねぎと卵を加えて混ぜる;


:スープを盛り付ける;

:完成;
stop
@enduml
