@startuml 副菜を作る
|ユーザー|
:スーパーで食材を購入;
start




fork
  :お湯を沸かす;
fork again
  :ほうれん草を洗う;
  :茎の部分を切り落とす;
  
  
end fork

:ほうれん草をゆでる;
:茹で上がったほうれん草を冷水に浸す;
:ボウルにほうれん草、醤油を入れ混ぜる;
:ほうれん草を適切な長さに切る;


:皿に盛り付ける;
:かつお節をふりかける;

:完成;
stop
@enduml
