@startuml 主菜を作る
|ユーザー|
:スーパーで食材を購入;
start


:ピーマンを洗う;
:ピーマンを縦に半分に切り種を取り除く;
:玉ねぎをみじん切りにする;
:ボウルに挽肉、玉ねぎ、パン粉、牛乳、塩、胡椒、醤油を加える;
:よく混ぜて肉だねを作る;
:ピーマンに肉だねを詰める;


:熱したフライパンに油を敷く;
:肉だねを下にしてピーマンをフライパンに並べる;
:焼き色がついたら、ひっくり返して蒸し焼きにする;


:焼きあがったピーマンの肉詰めをさらに盛り付ける;


stop
@enduml
